services:
  planner-ui:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: shift_planner_ui
    ports:
      - "8888:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - deploy_backend

networks:
  deploy_backend:
    external: true
